create table if not exists _user
(
    id       bigint generated by default as identity primary key,
    name     varchar(50)        not null,
    username varchar(20) unique not null,
    password varchar(60)        not null,
    role     varchar(10)        not null,
    active   boolean            not null default true
);

insert into _user(name, username, password, role)
values ('Admin', 'admin', '$2a$12$.fZVOwvB6kOfcEHDpaLfjehC7tmFNDm6pnFkBzaQPKAgo3xBbspda', 'ADMIN')