create table student
(
    id bigint generated by default as identity primary key,
    name varchar(50) not null
);

insert into student(name)
values ('x');

insert into student(name)
values ('a');

insert into student(name)
values ('b');

insert into student(name)
values ('c');

insert into student(name)
values ('d');